#pragma once

enum networkingErrors {
	NETWORK_OK = 0,

	WSA_STARTUP_ERROR = 10,

	GET_ADDR_INFO_ERROR = 20,

	CREATE_SOCKET_ERROR = 30,
	CONNECT_SOCKET_ERROR = 31,
	ALL_CONNECTING_SOCKETS_ERROR = 32,

	SET_NONBLOCKING_ERROR = 40,
};